name: docker-diu # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Updates the docker images downloaded in the system # 79 char long summary
description: |
      Updates the docker images downloaded in the system and you also can specify
      specific images to update. Furthermore, you also can prune the dangling images

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  diu:
    command: bin/diu


parts:
  diu:
    plugin: python
    source: .